# Generated by Django 3.0.5 on 2020-05-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ('-id',)},
        ),
    ]
