# Generated by Django 3.0.5 on 2020-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200523_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='case_paper',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
